last_name = "b"
recent_servers = [
    "192.168.1.244:8080",
    "192.168.1.210:8080",
    "192.168.1.211:8080",
    "192.168.1.14:8080",
    "192.168.1.57:8080",
]
mouse_sensitivity = 0.04999999701976776
