last_name = "b"
recent_servers = [
    "192.168.1.163:8080",
    "192.168.1.210:8080",
    "192.168.1.14:8080",
    "192.168.1.57:8080",
    "192.168.0.104:8080",
]
mouse_sensitivity = 0.1900000274181366
